### PR TITLE
strife: Add misc. Crispy features

### PR DESCRIPTION
**Pull request by ceski-1**

### CODE REVIEW

**Comment by ceski-1** [comment]
Misc. sound fixes:
1. Play `sfx_swtchn` if menu is activated with a different key than ESC.
2. Door "oof" originates from player.
3. Play sound effect when a door is opened again while going down.
4. Play sound effect when a door is closed manually.
5. [Play ambient sounds consistently](https://doomwiki.org/wiki/Strife_ambient_sounds_are_inconsistent).
6. Don't play "oof" sound when dead.
7. [Play "oof" sound for Irale's door](https://doomwiki.org/wiki/Irale_door_missing_sound_bug).

**Comment by ceski-1** [comment]
References:

Preserve targets/tracers in saved games:
https://doomwiki.org/wiki/Strife_save_game_target_loading_glitch
https://doomwiki.org/wiki/Strife_save_game_tracer_loading_glitch

Preserve monster skill when loading a game:
https://doomwiki.org/wiki/Monsters_reset_to_normal_when_loading_a_save_game

**Comment by ceski-1** [comment]
There's something I'd like to fix but didn't yet. There are a bunch of these skill level adjustments for the Bishop that are backwards:

https://github.com/fabiangreffrath/crispy-doom/blob/d82b9b2f861678013595320223e14b93d425091a/src/strife/g_game.c#L2146-L2147

From the wiki:

> Due to a coding error, the Bishop's missiles move twice as fast on Training skill level and half as fast on Bloodbath. This makes the Bishop easier to kill on higher skill levels.

Would it be acceptable to fix this, but for casual play only (when `crispy->singleplayer` is `true`)? My instinct is no and to leave it alone.

**Comment by fabiangreffrath** [comment]
> Would it be acceptable to fix this, but for casual play only (when `crispy->singleplayer` is `true`)? My instinct is no and to leave it alone.

I'd rather leave it unchanged. The gaming experience should be identical regardless if recording a demo or not. Imagine you practice killing the Bishop without recording and once you feel you've got it you want to record it. *bummer*

**Review by fabiangreffrath — APPROVED** [review]

**Comment by ceski-1** [comment]
That was my thinking as well. The other changes are conservative and similar to Crispy Doom.

**Pull request merged**
