### PR TITLE
Change extended map colours to be closer to vanilla's

### PR DESCRIPTION
**Pull request by kitchen-ace**
Changes the wall colours to be closer to vanilla, and changes the key
wall colours slightly to differentiate them a bit more. With the key
linedefs now flashing, I think it's easy enough to spot them on the map.

### CODE REVIEW

**Comment by kitchen-ace** [comment]
MAP04 screenshot. I find it quite easy to distinguish key walls from non-key walls like this but eyes and monitors aren't standardized.

mapcol

**Comment by JNechaevsky** [comment]
I apologize for my two cents: there is a vignette in initial Raven's anitialiasing code. Not really necessary, but looking awesome:

screenshot-doom-02

Maybe it's worth to keep it.

**Comment by fabiangreffrath** [comment]
Hm, I must admit the new scheme doesn't look bad, but in general I don't want to give up the Boom automap colors.

**Comment by kitchen-ace** [comment]
>Hm, I must admit the new scheme doesn't look bad, but in general I don't want to give up the Boom automap colors.

That's a valid argument. To be honest I didn't even realize they were the same as in Boom.

**Comment by fabiangreffrath** [comment]
Yep, it's "the original extended automap".

**Comment by kitchen-ace** [comment]
What about adding it as an option to Extend Automap Colors? Toggle between Boom, Doom-like, Off

**Comment by fabiangreffrath** [comment]
As you probably remember, I *hate* options. Especially purely subjective choices like this.

I mean, this will open a can of worms. Where does this lead to? Doom with a bit of Boom, Boom without colored doors, Colored secrets but no colored revealed secrets, white exit lines but no green teleporters, etc. You see what I mean.

**Comment by kitchen-ace** [comment]
>As you probably remember, I hate options. Especially purely subjective choices like this.

Of course, but they do have their merits sometimes. Also, adding one other choice doesn't mean you need to acquiesce to every possible preference\*, and I'm willing to compromise on this new choice if there's some sort of consensus for an alternate scheme among other Crispy users.

\*The idea to customize colours for every linetype, like in PrBoom+, isn't something I'd dare suggest ;)

Anyhow, I'll leave it up to you to decide what to do with the PR, no hard feelings if you just reject and close it.

**Comment by fabiangreffrath** [comment]
It would be a lot easier to apply this if it wouldn't mean to second guess the original Boom authors' choice from 22 years ago. 😕

**Comment by kitchen-ace** [comment]
>It would be a lot easier to apply this if it wouldn't mean to second guess the original Boom authors' choice from 22 years ago.

Keeping the Boom colours because you like them or have some attachment to them is one thing, but I'm not sure trying to preserve their intent is a good criteria for changing/not changing things. Boom itself was in development for less than two years, and like you said it was over two decades ago. 

Anyhow, another point in favour of red walls: sometimes you're meant to see secret doors etc. on the automap, since that's the only clue. Here's a map with the normal Crispy Extended colours, can you spot the secret doors?
DOOM0001

How about with the ones in this PR?
DOOM0003

Here are the unextended colours:
DOOM0002

**Comment by fabiangreffrath** [comment]
Oh, wow!

**Pull request merged**
