### PR TITLE
Heretic: first implementation of Crispness menu

### PR DESCRIPTION
**Pull request by JNechaevsky**
This the very first implementation of Crispness menu for Crispy Heretic. 

@fabiangreffrath, please remember, it was your idea! :no_mouth:

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Phew, right first try! :blush:
I wonder what's wrong with coloring, i.e. this:
```
    // Subheaders
+++ dp_translation = cr[CR_GOLD];
    MN_DrTextA("RENDERING", 63, 30);
    MN_DrTextA("NAVIGATIONAL", 63, 60);
+++ dp_translation = NULL;
```

...gives this result: [screenshot](https://user-images.githubusercontent.com/21193394/73213020-7db68180-4160-11ea-958a-5a29b1705cba.png). In RD I'm using your old, tablified approach and still not very familiar with `rgb_to_hsv`. Even no idea where to start investigation. 

However, I see you still have some tables here: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/v_trans.c#L38. Maybe I should add my own from here: https://github.com/JNechaevsky/russian-doom/blob/master/src/v_trans.c#L422? Or we should preffer to investigate what's wrong with HSV?

**Comment by fabiangreffrath** [comment]
Static tables stink, let's not use them. HSV tables want to be initialized, though. :wink:

**Comment by fabiangreffrath** [comment]
https://github.com/fabiangreffrath/crispy-doom/blob/24bca9117677376b30fc212d6e78e61484eca7af/src/doom/r_data.c#L1211

**Comment by JNechaevsky** [comment]
@fabiangreffrath thanks for pointing out! I'll get my hand sooner on later to coloring code. But before, we have to discuss our next step - how should we apply coloring to this?
```
    // Show level stats
    MN_DrTextA(crispy->automapstats == WIDGETS_OFF ? "NEVER" :
               crispy->automapstats == WIDGETS_AUTOMAP ? "IN AUTOMAP" :
                                                         "ALWAYS", 190, 70);
```
I mean, how should we properly write coloring code for two _green_ and one _red_ without separating to three different `if` conditions?

Another important thing: for now, `x,y` values for `on/off` features are hardcoded. This replicates vanilla code, but will not be friendly for possible replaced font. It's not a big deal until there are just a few features (a) and lack of interest for Crispy Heretic development & support for everything (b), but in far future we should use Crispy Doom style.

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath thanks for pointing out! I'll get my hand sooner on later to coloring code. 

For Heretic, you shouldn't need the `keepgray` option and simply pass `false` in its place.

> But before, we have to discuss our next step - how should we apply coloring to this?

You contruct a string with `M_snprintf()` that contains both the color indicator string (`crstr[]`) and the actual string you want to print. Then you pass *this* string over to `MN_DrTextA()`. This is how it's done in the `M_DrawCrispness*()` functions in Crispy Doom.

**Comment by JNechaevsky** [comment]
Oh yes, I've seen it, but never tried to understand/replicate. Guess, finally the time has come.
Also wondering how initially gray colors will be colored via HSV. 🤔

**Comment by fabiangreffrath** [comment]
The S in HSV is for Saturation. You can turn any color into grey, but you can also turn grey into any colour. It's fantastic!

**Comment by JNechaevsky** [comment]
Just tried to add coloring, it's working and looks awesome!
image

But it's still `dp_translation`, better I'll use if for subheaders like "Rendering" and "Navigational".

May I commit changes in `R_InitColormaps` first? Understanding of how to compose on/off strings will take much more time. Also, I'm not quite sure I've got everything right about `keepgray`. Heretic's HUD digits are not using gray color at all, so should it be this?

```
    // [crispy] initialize color translation and color strings tables
    {
	byte *playpal = W_CacheLumpName("PLAYPAL", PU_STATIC);
	char c[3];
	int i, j;
	boolean keepgray = false;
	extern byte V_Colorize (byte *playpal, int cr, byte source, boolean keepgray109);

	if (!crstr)
	    crstr = I_Realloc(NULL, CRMAX * sizeof(*crstr));

	// [crispy] check for status bar graphics replacements
>	// i = W_CheckNumForName(DEH_String("sttnum0")); // [crispy] Status Bar '0'
>	// keepgray = (i >= 0 && W_IsIWADLump(lumpinfo[i]));

	// [crispy] CRMAX - 2: don't override the original GREN and BLUE2 Boom tables
	for (i = 0; i < CRMAX - 2; i++)
	{
	    for (j = 0; j < 256; j++)
	    {
		cr[i][j] = V_Colorize(playpal, i, j, keepgray);
	    }

	    M_snprintf(c, sizeof(c), "%c%c", cr_esc, '0' + i);
	    crstr[i] = M_StringDuplicate(c);
	}

	W_ReleaseLumpName("PLAYPAL");
    }
```

Because using a `false` in `cr[i][j] = V_Colorize(playpal, i, j, false);` gives a compiler warning:
```
r_data.c:541:10: warning: variable 'keepgray' set but not used [-Wunused-but-set-variable]
  541 |  boolean keepgray = false;
```

**Comment by fabiangreffrath** [comment]
Sure, you can use dp_translation. Regarding keepgrey, just kick it out entirely and call V_Colorize() with last parameter being false.

**Comment by fabiangreffrath** [comment]
Whereas, once you have reached this point, it's probably easier to just use the crstr[] method.

**Pull request merged**
