### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by JNechaevsky**
Changes from https://github.com/fabiangreffrath/crispy-doom/pull/921. Is everything correct?

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Looks good, thank you! I'd like to wait for the non-Doom icon situation to settle in Choco first. So, does anything speak against a formal release within the next few days?

**Comment by JNechaevsky** [comment]
Sure, whatever you say. Nothing against from my side. I have promised to suggest some extra ideas for multiplayer, but none of them are critical and major part of DM demos and spy mode is already here. Here's what I have, everyone is welcome for discussion.

**1. Colored demo timer**
Not really that necessary, just a small eye-candy aid. Green for playback, yellow for paused states, red for recording. From another hand, coloring logic is slightly complicated here and we definitely don't want another micro switch. Plus, demo bar is white which makes color matching just perfect.

**2. Replace K/I/S stats with G:/I:/B:/R: frags counter**
Very and very useful for death match, live and demo. Even without sorting by first place frags. Implementation itself is [pretty easy](https://github.com/JNechaevsky/inter-doom/pull/370/commits/baef74765e6c1960dd4f1b12b4673e1fadbcf491) _(oh, but wait, here we have vanilla ST widget system...)_ and result may look like this, from ID: [screenshot](https://user-images.githubusercontent.com/21193394/184480541-9cf42598-2871-42a2-acd5-426c04272260.png).

**3. Move K/I/S widgets one line down in network game**
So chat line will be able to appear.

**4. Replace level time widget with -timer value.**
Could be pretty handy, but -timer itself is available in deathmatch mode only.

**Comment by mikeday0** [comment]
> Looks good, thank you! I'd like to wait for the non-Doom icon situation to settle in Choco first. So, does anything speak against a formal release within the next few days?

In case you didn't notice: https://github.com/chocolate-doom/chocolate-doom/pull/1492 :wink:

**Comment by JNechaevsky** [comment]
Actually, we have one little blocker: old version of SDL 2.0.22 in MSYS, while 2.24.0 is officially out.

@SirBofu upraised a [screen freezing](https://www.doomworld.com/forum/topic/112333-this-is-woof-1020-aug-11-2022-updated-winmbf/?do=findComment&comment=2536771) issue at Doom World, and probably is it worth to wait a little bit and delay release until we'll have 2.24.0 in MSYS itself. My very quick test showed that screen freezing is fixed without "Win11 idiocy" fix, but better don't go hurry in this case. 

I suggest to:

1. Wait until 2.24.0 will be in MSYS.
2. Once updated, we can double-check if freezing is fixed. AFAIR, it happens even on virtual machines, and fortunately I have VMs with XP, 7, 8.1 and 10 at hand, while 11 is my live system.
3. If everything is okay, we can remove "idiocy" fix good and have a green light.

**Comment by fabiangreffrath** [comment]
Alright, sounds like a plan, thank you!

**Comment by fabiangreffrath** [comment]
This happens because sigil.wad is sideloaded and their TEXTURE lumps clash. If you pass the `-nosideload` parameter, it should work.

**Comment by rfomin** [comment]
> @SirBofu upraised a [screen freezing](https://www.doomworld.com/forum/topic/112333-this-is-woof-1020-aug-11-2022-updated-winmbf/?do=findComment&comment=2536771) issue at Doom World, and probably is it worth to wait a little bit and delay release until we'll have 2.24.0 in MSYS itself. My very quick test showed that screen freezing is fixed without "Win11 idiocy" fix, but better don't go hurry in this case.

We updated the SDL to 2.24.0 for the MSVC Woof build, so from @SirBofu's report it looks like the screen freeze issue is still not resolved? I don't have Windows 11 to test.

**Comment by JNechaevsky** [comment]
Must be it, I can't remember for sure was it happening in previous versions of SDL (2.0.18 and below), but remember for sure it starts happing on Windows 11 after one of cumulative updates and @fabiangreffrath confirmed that it start to happen after some of updates on Windows 10.

@rfomin, could you please explain - DLL for the MSVC Woof build, is it building from source, or is it just DLL from released version? I.e. on of these links:

- https://github.com/libsdl-org/SDL/releases/download/release-2.24.0/SDL2-2.24.0-win32-x64.zip
- https://github.com/libsdl-org/SDL/releases/download/release-2.24.0/SDL2-2.24.0-win32-x86.zip

**Comment by JNechaevsky** [comment]
Oh Christ, yes, it's happening in Woof with SDL 2.24.0. Commenting or removing these lines helps: https://github.com/fabiangreffrath/woof/blob/master/src/i_video.c#L1509-L1512

For some reason, freezing is not happening in InterDoom with SDL 2.24.0 and removed condition, that's why I though it fixed entirely.

**Comment by rfomin** [comment]
> @rfomin, could you please explain - DLL for the MSVC Woof build, is it building from source, or is it just DLL from released version? I.e. on of these links:
> 
> * https://github.com/libsdl-org/SDL/releases/download/release-2.24.0/SDL2-2.24.0-win32-x64.zip
> * https://github.com/libsdl-org/SDL/releases/download/release-2.24.0/SDL2-2.24.0-win32-x86.zip

It's from released version, we download it in CMake: https://github.com/fabiangreffrath/woof/blob/d51fdc9fb2b01c65730b42940390e67bb163784c/CMakeLists.txt#L72-L96

**Comment by JNechaevsky** [comment]
Understood, thanks. Well... I guess better to keep "idiocy" fix then, but either add 2.24.0 version checking condition for  Crispy and Woof, or even better somehow make `>= 2.0.22` check since there is simply no guarantee that freezing will be fixed in next SDL version or it will be fixed at all. 

It's definitely not a Crispy/Woof code issue, vsync toggling was working fine for years.

**Comment by rfomin** [comment]
> better somehow make `>= 2.0.22` check since there is simply no guarantee that freezing will be fixed in next SDL version or it will be fixed at all.

This is a Windows 11 Direct3D 9 issue if I understand correctly. Anyway, earlier in such cases we added checks for the new version. Another solution is to switch to the "direct3d11" SDL driver, but then the screenshots won't work.

**Comment by JNechaevsky** [comment]
I wonder if [SDL2_image](https://github.com/libsdl-org/SDL_image) may help. Apparently, if have native [IMG_SavePNG](https://wiki.libsdl.org/SDL_image/IMG_SavePNG) function for taking PNG screenshots.
But what's more interesting: `direct3d11` giving far better `-timedemo` results than standard `direct3d` (is it version 9?). Almost as fast as OpenGL ES v2. 😮

**Comment by rfomin** [comment]
> I wonder if [SDL2_image](https://github.com/libsdl-org/SDL_image) may help. Apparently, it have native [IMG_SavePNG](https://wiki.libsdl.org/SDL_image/IMG_SavePNG) function for taking PNG screenshots.

I think `IMG_SavePNG` is just saving the buffer to PNG and the problem is in the `SDL_RenderReadPixels` function. Do the screenshots work with direct3d11 in Inter Doom?

> But what's more interesting: `direct3d11` giving far better `-timedemo` results than standard `direct3d` (is it version 9?). Almost as fast as OpenGL ES v2.

On my system there is no difference between direct3d(9) and direct3d11 performance and OpenGL ES is slower than regular OpenGL but I have a relatively old GPU.

**Comment by JNechaevsky** [comment]
> Do the screenshots work with direct3d11 in Inter Doom?

Nope, just black image with size of display resolution. My knowledge of SDL is very limited, so I can't suggest anything father.

> On my system there is no difference between direct3d(9) and direct3d11 performance and OpenGL ES is slower than regular OpenGL but I have a relatively old GPU.

Ah, what is supported version of Direct3D on your video card? You can check it by using Win+R -> `dxdiag`, second tab ([screenshot](https://user-images.githubusercontent.com/21193394/186745249-3ea71c3e-74ba-4499-b676-055fbe7c9eb8.png)).

What is really odd, in SDL version 2.0.22 it was possible to set a simple hint to get Open GL ES v2:
```
// Somewhere in the beginning of SetVideoMode
SDL_SetHint(SDL_HINT_RENDER_DRIVER, "opengles2");
```
Starting from version 2.23.2 pre-release it is broken, I got just a black screen, matter no is it windowed mode or full screen.

**Comment by rfomin** [comment]
> Nope, just black image with size of display resolution.

Yep, it's the same on my Windows 10 system in Woof.

> Ah, what is supported version of Direct3D on your video card?

It's Direct3D 12. I think Direct3D 9/11 performance depends on the combination of video driver/OS version and GPU generation.

**Comment by JNechaevsky** [comment]
SDL 2.24.0 is out for MSYS! ([screenshot](https://user-images.githubusercontent.com/21193394/186981018-8469e7bc-eb5a-42d0-a872-8c112121f118.png))

**Pull request merged**
