### PR TITLE
Update CodeBlocks project version to 5.0-beta1

### PR DESCRIPTION
**Pull request by JNechaevsky**
Here it is, an SDL2 update for Crispy's Code::Blocks project!

Notable things:

- Version has been set to `5.0-beta1`, as declared in https://github.com/fabiangreffrath/crispy-doom/blob/master/configure.ac.
- Other than Doom projects has a little and safe cleanup, just for future.
- No changes were made in the Crispy code.
- Definition of `NET_PACKAGE_STRING "Chocolate Doom 2.3.0"` has been removed.
- Setup icon/executable info (file properties) now appearing after compilation.

All app icons are fine: http://screenshot.ru/upload/images/2017/10/10/595cba.png

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I don't see any mention of crispy-specific files like e.g. `p_blockmap.c`? Are you sure you have added everything to get a working compile?

Are you okay if I squash-merge this, i.e. combine all your changes into one commit and merge that?

**Comment by JNechaevsky** [comment]
Dammit... Thanks for checking. Looks like I've got some kind of desync in local hdd <> github. Here is all fixed files in my Crispy fork: https://github.com/JNechaevsky/crispy-doom/commit/0754d0ec2448f6539ecc879879c903067aa12f23

I'm absolutely okay with this, because committing into other that mine project is still something hard for me, to be honest. I really have no idea how to get rid of _"added some commits"_ stuff while commiting only necessary stuff.

**Comment by fabiangreffrath** [comment]
> to be honest. I really have no idea how to get rid of "added some commits" stuff while commiting only necessary stuff.

You need to add your changes to a new branch that is based on a clean crispy-doom master branch. Once you committed all your changes to that new branch, you file a pull request against the crispy-doom master branch, and once I merged it there, you merge it back into your master branch.

**Comment by JNechaevsky** [comment]
Thank you for explanation and merge. Guess I have some understanding what actually branch is, so I'll try to make a proper commit next time.

**Pull request merged**
