### PR TITLE
Heretic: upgrade renderer to use 32-bit integer math

### PR DESCRIPTION
**Pull request by JNechaevsky**
Values are verified with current Crispy Doom.

Game/timedemos working fine. Coding style preserved (well, for 99%).
This will not change anything visually, but makes a green light for further limit removing changes.

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Looks likes I can't make two different pull requests while working in one branch. Just :boom: great.

Any way, the result of slime trails removing in action, before and after.

**Comment by fabiangreffrath** [comment]
> Looks likes I can't make two different pull requests while working in one branch. Just 💥 great.

Yes, you can only have one branch per pull request. And it is good this way. See, I just cannot merge your 32-bit render upgrade now, because you added the slimetrail fix on top of it, and the latter is a prime example for code that took some modifications after its initial addition. The `px` and `py` are now called `r_x` and `r_y` respectively and the "Linguortal" detection has been added. Please understand that I want the code to be identical across all games at any time, else code maintenance will grow into something very frustrating soon. So, I just cannot merge it as it currently is. :/

**Comment by JNechaevsky** [comment]
Ehh. So what shall we do now? I think we need to reject this PR, but what's the plan of further proper committing? I'm okay if they will be one per branch with waiting for you approval, but the current problem - I don't know what exactly should be merged step-by-step to make all the things proper.

I completely understand and respect your coding principles, but please always remember: I can only verify and deeply test such a technical enhancements / limit-removing things. But not technically understand them. That's why I have tested this code modifications and opened PR.

**Comment by fabiangreffrath** [comment]
All is fine! We could either create a new branch from the fist commit of the current branch, or we state an exception and fix the current branch in order to merge it. I think I'll do the second.

For the future, let's please keep a "one branch for one feature for one pull request" concept. ;)

**Comment by JNechaevsky** [comment]
Phew, thanks! Sure, will do as you say: one PR, one branch, one feature/fix.

Let's define next step? Following out table it should be "Fix wobbling long walls", which consists of six commits. But can all of them be applied in one PR? In keeping with the order of priority of course. I think it will be safe to to, since all of them are only "wobble" related.

**Comment by JNechaevsky** [comment]
Oh, please. The "wobbling" problem is real in vanilla, more of that, it's real **much more** than it should be. I'll send you a voiced video that will demonstrate this bug live in vanilla level. There also will be a small demonstration of Tutti-Frutti effect on the sprites, which was not happened in Doom, but it's just for further step.

Have to agree about Medusa, I was not lucky in porting this fix in Heretic.

**Comment by fabiangreffrath** [comment]
> which consists of six commits. But can all of them be applied in one PR?

The six commits give a hint which code needs to be changed, this code is then to be taken as-is from Doom.

**Comment by JNechaevsky** [comment]
I'm starting to get confused by trying to get everything verified with current Doom code, this is too much far out of my limits. Some code is notably changed, so it's even not possible to compile the executable. I can't proceed this way, neither I can't handle it. Sorry. :(

At the moment I'm ready to make a PR with applied:
- https://github.com/fabiangreffrath/crispy-doom/commit/2cd6aeb12d6881c838d03f06ec95132f498d7c2d
- https://github.com/fabiangreffrath/crispy-doom/commit/95b1e1a71e098a8cd533aef7bfd66b3dc9908198
- https://github.com/fabiangreffrath/crispy-doom/commit/11c7be0211e2de89e00fdcee6c7bacc52944edbf
- https://github.com/fabiangreffrath/crispy-doom/commit/6414c85d640e60eb9ef4f1db998901221aa05251

But further applying of https://github.com/fabiangreffrath/crispy-doom/commit/2a54d71b41c10375ad91c9689155e5f8b67699c5 is not possible because this:
- https://github.com/fabiangreffrath/crispy-doom/commit/98a1cb352dd85ef27d5f9533543328f157d9d8a1#diff-5bcf11c5834d899eba5dd38aa5e3acf2R80 
is replaced by this:
- https://github.com/fabiangreffrath/crispy-doom/pull/242/commits/a7464c997ef4c03e9d93db27fd14ff39587e554b#diff-82e0c449dd6eedf4a6d4aab2d1390e2cR72

Obviously for accordance to current Doom code. And what shall we do now?

**Comment by fabiangreffrath** [comment]
No problem here, we don't *have* to apply the same commits in the same order. If there is an intermediate step missing it is perfectly alright to apply what is needed by hand. On the other side, these commits merely give a pointer which code is to change and we can take it as is from the latest Doom code base.

**Pull request merged**
