### PR TITLE
Widescreen for good

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
@Zodomaniac It's okay for me, how about you?

**Comment by fabiangreffrath** [comment]
I wanted to squash-merge this...

**Comment by fabiangreffrath** [comment]
... and close #553 in the commit message.

**Comment by Zodomaniac** [comment]
Oh, I'm sorry. I thought that if you had said OK, I'm free to merge if I accept it.

**Comment by fabiangreffrath** [comment]
Not exactly, but it's okay now.

**Pull request merged**
