### PR TITLE
Adding Quick Reverse Key to Hexen / Heretic

### PR DESCRIPTION
**Pull request by Noseey**
Related Issue:
Closes https://github.com/fabiangreffrath/crispy-doom/issues/1239

**Change Summary**

- Adding Quick Reverse Button (mouse and keyboard) to Heretic and Hexen.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
> * Improving turn Button behavior in all three games (Doom, Heretic, Hexen) by only turning once per press. (especially for mouse-bound quick reverse, this will be helpful)

Thank you, but I don't understand why the previous approach of resetting the corresponding mouse and button states doesn't work?

**Comment by Noseey** [comment]
> Thank you, but I don't understand why the previous approach of resetting the corresponding mouse and button states doesn't work?

It works mostly, as it skips further inputs until updates are done. For keyboard, this is negligible, as you would need to actively hold down the key to provoke further turns. For mouse-bound quick reverse, I did some testing with a mouse-thumb button and noticed that when turning, any slight mouse-movement causes subsequent turns. At least for me, it was difficult to use the quick reverse that way.

**Comment by Noseey** [comment]
I had some further thoughts about it and I think what I'm seeing e. g. in the case of the quick reverse key input is the typical keyboard interrupt behavior on my hardware and OS. The first interrupt is sent "immediately" when pressing the key, while when holding the key, after ~1s the long-press triggers continual interrupts. This is why I don't notice it practically when playing, as I rarely press and hold the quick reverse key for that long. I suspect, it differs from OS and Hardware, maybe you are seeing something different here. 

As for the mouse, I suspect that the interrupts when moving it causes also the button state to refresh. This behavior could also differ with OS and Hardware. But that is just some speculation here, I didn't analyse it.

**Comment by Noseey** [comment]
As there seems to be other buttons affected by this aswell, I would propose the following:
I will roll back the improved behavior for this PR and instead create a new open issue to summarize my observations there and to allow for a separate discussion on the topic. What do you think?

**Comment by fabiangreffrath** [comment]
Yes, please. I was about to suggest something similar anyway.

**Pull request merged**
