### PR TITLE
Hexen: interpolate sky scrolling

### PR DESCRIPTION
**Pull request by JNechaevsky**
My [ancient implementation](https://github.com/JNechaevsky/international-doom/pull/68/commits/0d7144a252943d936f1b24a47c53c1d6fd1fb6f3) from ~2018 was pretty goofy and I even wasn't willing to suggest it, as it have a lot of flaws. This one is much simpler and cleaner, few remarks should be made though:
* It's not really about uncapped frame rate, it will work same even in capped 35 fps mode, but to keep things vanilla way, smoothing will be applied only in uncapped mode.
* Despite of `<< 6` multiplier is a magic number, it was heavily verified to represent original speeds (yep, they can be different in `MAPINFO`), and after running two game windows for about ~10 minutes, notable sky texture parts are still on sync. Thanks to @kitchen-ace for making this experiment as well!
* Please note, I haven't touched "Use sky 2" [block](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/r_plane.c#L531). It was supposed to draw second defined sky via `MAPINFO` in sectors with special `200`, but due to [oversight in the code](https://www.doomworld.com/forum/topic/140899-hexen-sector-special-200-alternate-sky/) it is not working on ceilings, just on floors. I have checked, none of original maps of Hexen and Hexen DK is using such special, so...
* I was trying to avoid using `angle2`, but no luck, unfortunately. 

Where to see all possible scrolling cases in action:
* `VISIT08` - double sky, two layers skies scrolling.
* `VISIT19` - double sky, one layer scrolling.
* `VISIT20` - single sky, one layer scrolling.

Kindly asking @mikeday0 to check it out, perhaps it can be done even more simpler or better?

### CODE REVIEW

**Comment by mikeday0** [comment]
This is a great fix Julia! I think the number `6` can be "de-magicked" by  defining it as `(ANGLETOSKYSHIFT - FRACBITS)`. If I'm following the code correctly, what you're doing is rearranging the math to avoid a loss of precision occurring in the original `Sky1ColumnOffset >> 16` operation. I do not consider this to be "interpolation" in the strict sense of the term but the resulting smoothness certainly has a similar appearance to interpolation.

**Comment by mikeday0** [comment]
Since this improvement can also be applied to 35 fps mode I personally think it could be a new Crispness option for Hexen.

**Comment by fabiangreffrath** [comment]
If this works equally well for both capped and uncapped modes then we don't need a switch. Then this is our new method. It's just cosmetic and nothing sync critical anyway.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by JNechaevsky** [comment]
Thanks! I even don't sure how to properly explain what is happening in the code, just took my old approach and after about one hour of experimenting got exactly what was needed. Testing and verifying speeds took extra hour of two, but running two game windows was good enough to see if notable parts of sky textures were in same places in both capped and uncapped window. By "notable places" I meaning fun thing - you know for sure the case when you looking to the clouds, imagination can "draw" something like face or some kind of detail. This worked exactly same way here, except there is a pixels here, not actual clouds. 🙂

Speaking of magical values, probably the most magical thing in Hexen is a calculation of [armor class](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/sb_bar.c#L1311): it's a game of `FRACUNIT`, `FRACBITS`, oh my... It's not even overflow safe - committing suicide or getting extreme damage (telefrag or falling from extremely tall height) overflows armor value and it goes up.

Few thoughts, for the record. I believe, Raven did not do such smooth scrolling by one of two reason:

1. They didn't tried such approach. This is completely okay and understandable. 
2. In low resolution mode, which was only available in Hexen, smooth scrolling looks a bit "cracky". This must not be a problem of smooth implementation itself - this is because of how sky columns are drawing, they are still taking `xtoviewangle` into account, i.e. it's sky texture is not a straight plane/texture. "Linear sky angle" feature helps a little bit, but doesn't solves this problem entirely. In 2x resolution, however, it looks pretty fine, and I'm afraid any farther attempt to turn sky texture into a straight plain texture will require serious rewriting of handling sky textures drawing.

**Pull request merged**
