### PR TITLE
Heretic: Make demoextend and shortticfix the default

### PR DESCRIPTION
**Pull request by kitchen-ace**
See https://www.doomworld.com/forum/post/2119904 for discussion.

### CODE REVIEW

**Comment by kitchen-ace** [comment]
I put the [crispy] comments underneath the code because otherwise they get added to the manpage comment block. Let me know if there's a better way to do this.

**Comment by fabiangreffrath** [comment]
Are we really sure we want to change the defaults here?

**Comment by fabiangreffrath** [comment]
I mean, I read a single opinion inthe linked thread, but is this really consensus?

**Comment by kitchen-ace** [comment]
Two opinions actually ;) (Kraflab and PVS)

I think changing the defaults for these behaviours is fine:

* `demoextend` allows demos to be recorded and played that are longer than one map. For playback there's really no downside for normal use: if the demo goes longer than one map and you don't use `demoextend`, playback just quits on exit. If the demo normally ends on map exit, using `demoextend` for playback makes no difference.

    For recording, if you want to record a demo longer than one map, you have to use `demoextend` for recording and playback, there's just no other option. If you record a single-map demo with `demoextend` it will still play back fine without it, you just won't get the intermission screen.

    Kraflab commented that playing back demos without `demoextend` is useful for getting the exact tic length of a demo, which is something they use for dsdarchive.com, but they were also one of the people to suggest making it the default.

* `shortticfix` just changes recording behaviour to make turning left and right behave the same; without it mouse turning behaviour is very sensitive when turning right, and very rough when turning left. (IIRC this was the case in Doom 1.2, which the Heretic source is based on, but got fixed by 1.9.) It doesn't affect playback at all. I can't imagine anyone intentionally not using this fix, and if they don't want it, the `noshortticfix` param is still there.

All that said, if you want more opinions, I can try to solicit a few more from other people that have been involved in Heretic demo recording.

**Comment by fabiangreffrath** [comment]
Impressive, thank for elaborating!

**Pull request merged**
