### PR TITLE
Interpolate automap drawing and panning

### PR DESCRIPTION
**Pull request by JNechaevsky**
Thanks @rfomin for composing it into one PR: https://github.com/fabiangreffrath/woof/pull/659

Zooming isn't touched _(pshaw!)_. Current problem: panning by mouse not working at all, some help could be very appreciated.

### CODE REVIEW

**Comment by rfomin** [comment]
@JNechaevsky Works, but not smoothly:
```diff
diff --git a/src/doom/am_map.c b/src/doom/am_map.c
index 29e43386..23a87f9d 100644
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -479,8 +479,8 @@ void AM_changeWindowLoc(void)
     // [crispy] accumulate automap panning by keyboard and mouse
     if (crispy->uncapped && leveltime > oldleveltime)
     {
-        incx = FixedMul(m_paninc.x + m_paninc2.x, fractionaltic);
-        incy = FixedMul(m_paninc.y + m_paninc2.y, fractionaltic);
+        incx = FixedMul(m_paninc.x, fractionaltic) + m_paninc2.x;
+        incy = FixedMul(m_paninc.y, fractionaltic) + m_paninc2.y;
     }
     else
     {
@@ -2062,7 +2062,7 @@ void AM_Drawer (void)
     }

     // Change X and Y location.
-    if (m_paninc.x || m_paninc.y)
+    if (m_paninc.x || m_paninc.y || m_paninc2.x || m_paninc2.y)
     {
         AM_changeWindowLoc();
     }
```

**Comment by mikeday0** [comment]
I think you need to guard this part of `AM_changeWindowLoc` with an `if (crispy->uncapped && leveltime > oldleveltime)`:
https://github.com/fabiangreffrath/crispy-doom/blob/b4c12b9f42c916054178a94d9dfb51fccce3feb0/src/doom/am_map.c#L505-L506

Then your original interpolated `incx` and `incy` calculations should be right.

**Comment by JNechaevsky** [comment]
Figured it out, was missing `m_paninc2.x || m_paninc2.y` conditions for changing X and Y locations.

I was forced to remove:
```
    // [crispy] reset after moving with the mouse
    m_paninc2.x = m_paninc2.y = 0;
```
Otherwise mouse panning is working with awful jerking. Mouse panning now smooth and fine, but there is still small problem: small chance that panning will keep moving for a small time.

**Comment by mikeday0** [comment]
Yeah, you definitely have to clear those variables to get the mouse panning to stop properly. 

This seems to work pretty well on my end. Not heavily tested though.

<details>
  <summary>Click for diff</summary>

```diff
diff --git a/src/doom/am_map.c b/src/doom/am_map.c
index a4863f55..13306001 100644
--- a/src/doom/am_map.c
+++ b/src/doom/am_map.c
@@ -263,6 +263,7 @@ static int 	lightlev; 		// used for funky strobing effect
 static int 	amclock;
 
 static mpoint_t m_paninc, m_paninc2; // how far the window pans each tic (map coords)
+static mpoint_t m_paninc_target;
 static fixed_t 	mtof_zoommul; // how far the window zooms in each tic (map coords)
 static fixed_t 	ftom_zoommul; // how far the window zooms in each tic (fb coords)
 
@@ -470,8 +471,19 @@ void AM_findMinMaxBoundaries(void)
 void AM_changeWindowLoc(void)
 {
     int64_t incx, incy;
+    static int old_gametic;
 
-    if (m_paninc.x || m_paninc.y || m_paninc2.x || m_paninc2.y)
+    if (gametic > old_gametic)
+    {
+        m_paninc_target.x = m_paninc.x + m_paninc2.x;
+        m_paninc_target.y = m_paninc.y + m_paninc2.y;
+        old_gametic = gametic;
+
+        // [crispy] reset after moving with the mouse
+        m_paninc2.x = m_paninc2.y = 0;
+    }
+
+    if (m_paninc_target.x || m_paninc_target.y)
     {
 	followplayer = 0;
     }
@@ -479,13 +491,13 @@ void AM_changeWindowLoc(void)
     // [crispy] accumulate automap panning by keyboard and mouse
     if (crispy->uncapped && leveltime > oldleveltime)
     {
-        incx = FixedMul(m_paninc.x + m_paninc2.x, fractionaltic);
-        incy = FixedMul(m_paninc.y + m_paninc2.y, fractionaltic);
+        incx = FixedMul(m_paninc_target.x, fractionaltic);
+        incy = FixedMul(m_paninc_target.y, fractionaltic);
     }
     else
     {
-        incx = m_paninc.x + m_paninc2.x;
-        incy = m_paninc.y + m_paninc2.y;
+        incx = m_paninc_target.x;
+        incy = m_paninc_target.y;
     }
     if (crispy->automaprotate)
     {
@@ -2059,7 +2071,8 @@ void AM_Drawer (void)
     }
 
     // Change X and Y location.
-    if (m_paninc.x || m_paninc.y || m_paninc2.x || m_paninc2.y)
+    if (m_paninc.x || m_paninc.y || m_paninc2.x || m_paninc2.y ||
+            m_paninc_target.x || m_paninc_target.y)
     {
         AM_changeWindowLoc();
     }

```
</details>

**Comment by JNechaevsky** [comment]
Thanks, can confirm that it worked perfectly!

**Comment by JNechaevsky** [comment]
All done.

**Comment by fabiangreffrath** [comment]
Thank you!

**Comment by mikeday0** [comment]
Sorry to be a bother but the parallax scrolling in Heretic/Hexen is a little broken after this PR. I see two issues:
1) When not in follow mode, the map and background are supposed to scroll at the same speed when panning. Right now, the background is scrolling much faster than the map. (Hilariously faster if you turn off vsync). Still works fine at 35 Hz.
2) When zoomed in past a certain point, the background scrolling doesn't stop when trying to pan past the map edges. Also the panning becomes diagonal in direction? Very strange.

@JNechaevsky Would you like to take a look? I don't mind having a go at it if you are busy or perhaps tired of looking at automap code. :smile:

**Comment by JNechaevsky** [comment]
> I don't mind having a go at it if you are busy or perhaps tired of looking at automap code. 😄

Thanks for understanding. I swear, the best way to go is keep that darn background static! If you have a working solution, please proceed - I'm afraid, for me it will take much longer to understand/fix both cases.

**Comment by mikeday0** [comment]
I know what you mean! I had the same thought when I was working on widescreen support. However I didn't think it would Crispy-like to abandon something that was in vanilla, so I kept at it.

FYI. Looks like the diagonal panning is a vanilla bug. You have to zoom in really close though to trigger it though. Luckily, we can easily fix that here. Just check for `incx` and `incy` being non-zero before updating the `mapxstart` and `mapystart` values in `AM_changeWindowLoc()`.

I should hopefully have something to submit this evening.

**Pull request merged**
