### PR TITLE
Heretic and Hexen column drawing updates

### LINKED ISSUE #859: [Feature] Hexen: Support for widescreen replacement sprites
Current Hexen builds still have issues with some widescreen replacements for some weapon sprites.

Some of the patch columns contain posts >128px, causing the graphics to be drawn at wrong locations. This vanilla limitation has been already lifted for Doom and Heretic, but is still missing in Hexen.

### PR DESCRIPTION
**Pull request by mikeday0**
Add tutti-frutti fix which also happens to remove the 128 pixel post limit. (Fixes #859)
Add support for DeePsea tall patches.

I'm not especially confident that I properly implemented this so if you see anything funny or wrong, don't hesitate to say so!

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
This is missing the `(pl->picnum == skyflatnum)` case in `R_DrawPlanes()`, but that's probably less relevant.

**Comment by mikeday0** [comment]
> This is missing the `(pl->picnum == skyflatnum)` case in `R_DrawPlanes()`, but that's probably less relevant.

No problem, I'll add that as well.

**Comment by fabiangreffrath** [comment]
The commit message is not quire right, because the sky "plane" is an actual texture - but I trust the fix to be correct anyway. :wink:

**Comment by mikeday0** [comment]
> The commit message is not quite right, because the sky "plane" is an actual texture - but I trust the fix to be correct anyway. 😉

Sorry, I guess I had been looking at that block of code so much that the words "sky" and "plane" started to merge together in my head. Okay if I force-push to amend the message?

While I'm at it, should I update Heretic as well? The tutti-frutti fix is missing from its `R_DrawPlanes()` and the other column drawing functions.

**Comment by fabiangreffrath** [comment]
No need to force-push just to get a commit message right. I'll squash-merge commits anyway if they form a logical unit. Sure, if you'd like to fix Heretic as well while at it, feel free to do so.

**Comment by NightFright2k19** [comment]
Will this also fix widescreen assets in Heretic (and probably Hexen as well) to still require offsets? In Doom you can leave a widescreen statusbar replacement at [0,0] and it would be shown centered, while in Heretic, offsets would still have to be applied to the image.

**Comment by fabiangreffrath** [comment]
Sure, whatever the community demands. But let's please not stuff everything into this one PR. 😉

**Comment by NightFright2k19** [comment]
Alrighty. Do you need another issue opened for this or it's going to fly "under the radar"?

**Comment by fabiangreffrath** [comment]
I guess it's just porting over of the pendant of this line to the other games:
https://github.com/fabiangreffrath/crispy-doom/blob/ca4e704e1ee8e9114e8f73aa73ef9d5ebfadb079/src/doom/st_stuff.c#L523

**Comment by NightFright2k19** [comment]
Yeah. In the end, it's just about unifying the handling of widescreen assets throughout all the available games. Besides the fact that it makes the process easier. Admittedly, there are not that many custom Heretic/Hexen statusbars out there, but you never know what can happen.

**Review by fabiangreffrath — APPROVED** [review]
Ready for merging?

**Comment by NightFright2k19** [comment]
Thanks a lot, guys! I will test with the Heretic statusbar and the Hexen widescreen sprites tomorrow and let you know.

**Comment by rzhxiii** [comment]
I'll also test this for the next couple of days.

**Pull request merged**
