### PR TITLE
Allow toggleable menu items to be changed by arrow keys

### PR DESCRIPTION
**Pull request by JNechaevsky**
@fabiangreffrath, this is not over yet, I need your help with two items, which are still can be toggled only by `Enter` key:

**1. M_CrispyToggleWidescreen**

It's leading to `M_CrispyToggleWidescreenHook` function, which does not have a `choice` variable and thus, can't be scrolled back/left.

**2. M_CrispyToggleSndChannels**

It's leading to `S_UpdateSndChannels` which can only "add" or "increase" channels. Not sure what to do.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Indeed, these two cases may be show stoppers in some way. Unfortunately, it is currently impossible to  give these switches a direction in the menu.

First, for the widescren toggle, you cannot simply change screenbuffer resolution during a rendering operation (and you never know exactly when the buffer is rendered to screen with VSync enabled). Thus, I will have to apply the actual change in the post-rendering hook, which currently only calls the hook function, but doesn't pass a parameter.

Similarly for the sound channels. In order to change them, I need to stop all current channels and reallocate a new number of channels - and for this I need the stuff in s_sound.c. It is currently impossible to do inside the menu.

This will require a lot more work...

**Comment by JNechaevsky** [comment]
Duh. Clear, thanks. So what's our next plan then? We still can use `2` in menu structure for switching method, which will only work in "one right side" in current code.

**Comment by fabiangreffrath** [comment]
Well, I guess the `M_CrispyToggleWidescreen()` problem has solved itself in the current release, right?

**Comment by fabiangreffrath** [comment]
Closing orphaned issues and pull requests.

**Pull request closed without merging**
