### PR TITLE
update documentation structure

### PR DESCRIPTION
**Pull request by kiwphi**

### CODE REVIEW

**Comment by rfomin** [comment]
@kiwphi I restored Choco's documents, I hope you don't mind. Thank you for your work!

**Comment by kiwphi** [comment]
Sure, thanks for taking care of that @rfomin

**Review by fabiangreffrath — APPROVED** [review]
Is this ready for merging? It looks good to me, but I somehow lost track of this development during my holidays.

**Comment by kiwphi** [comment]
Let me do a final review to it first, I'll let you know when it's ready from my side

**Comment by kiwphi** [comment]
Everything is ready from my side. Now what remains is to implement the Github Actions to transfer everything from the docs/ directory into the wiki. @rfomin how shall we tackle this?

Wiki could be structured this way:

- Building
    - Building on Linux (build-linux.md)
    - Building on Windows (build-windows.md)
    - Building on Mac (build-mac.md)
- In-Game
    - Cheats (cheats.md)
    - Compatibility (compatibility.md)
    - Controls (controls.md)
    - Crispness Menu (crispness.md)
    - Command-line Parameters (params.md)
- FAQ (faq.md)
- Changelog History (changelog-history.md)

**Comment by rfomin** [comment]
Here is the GitHub action:
<details>
<summary>diff</summary>

```diff
diff --git a/.github/workflows/update-wiki.yml b/.github/workflows/update-wiki.yml
new file mode 100644
index 00000000..741f2b4e
--- /dev/null
+++ b/.github/workflows/update-wiki.yml
@@ -0,0 +1,36 @@
+name: update wiki
+
+on:
+  push:
+    branches: [ master ]
+    tags: ['*']
+  workflow_dispatch:
+
+jobs:
+  update-wiki:
+    if: ${{ github.repository == 'fabiangreffrath/crispy-doom' }}
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        with:
+          path: code
+      - name: Checkout wiki
+        uses: actions/checkout@v3
+        with:
+          repository: ${{github.repository}}.wiki
+          path: wiki
+      - name: Update files
+        run: |
+          rsync -a "./code/docs/" "./wiki/"
+      - name: Push to wiki
+        env:
+          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
+        run: |
+          cd wiki
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git diff-index --quiet HEAD || git commit -m "Update wiki" && git push
```
</details>

I created a wiki in my repository: https://github.com/rfomin/chocolate-doom/wiki

**Comment by kiwphi** [comment]
@rfomin awesome! I've updated all the readme links.
- Is there any way we can have the entry's name as a title instead of the file name? (e.g. "Command-line Parameters" instead of "params" as a title in [this page](https://github.com/rfomin/chocolate-doom/wiki/params) for example
- build-mac page doesn't seem to be populated

**Comment by rfomin** [comment]
> Is there any way we can have the entry's name as a title instead of the file name? (e.g. "Command-line Parameters" instead of "params" as a title in [this page](https://github.com/rfomin/chocolate-doom/wiki/params) for example

We can rename files in `docs/`, e.g. `params.md`->`Command-line-parameters.md`. Or rename them in GitHub action.

> build-mac page doesn't seem to be populated

Fixed. Here is sidebar code:
```md
### Building
* [Building on Linux](build-linux)
* [Building on Windows](build-windows)
* [Building on Mac](build-macos)

### In-Game
* [Cheats](cheats)
* [Controls](controls)
* [Crispness Menu](crispness)
* [Command-line Parameters](params)

##
* [Compatibility](compatibility)
* [FAQ](faq)
* [Changelog History](changelog-history)
```

**Comment by kiwphi** [comment]
Could we rename them in Github Actions? I think it would be better to have spaces in titles (instead of dashes), because we're not going to use spaces in the file names. Titles could be as below:
- Building on Linux
- Building on Windows
- Building on Mac
- New Cheats
- New Controls (with default bindings)
- Crispness Menu
- New Command-line Parameters
- Compatibility
- FAQ
- Changelog History

After that we're ready to merge. I guess there's no way to fully test everything in a separate branch, since the wiki is per project not per branch, so we'll have to make sure everything is working correctly after merging.

**Comment by rfomin** [comment]
> I think it would be better to have spaces in titles (instead of dashes), because we're not going to use spaces in the file names.

The dashes will be replaced with spaces by the wiki engine. So `New-Cheats.md` will look like `New Cheats`. I think it may not be necessary to keep the `docs/` directory, you can get the data directly from the wiki. Try to run `git clone https://github.com/rfomin/chocolate-doom.wiki.git`

**Comment by kiwphi** [comment]
Some title are longer than that and have extra text in them (such as "New Controls (with default bindings)").
Sorry but it seems like I have misunderstood how this works. I've kept the .md files in the repo (./docs dir) in order to be able to make PRs in order to modify the wiki entries. As far as I know, PRs for the wiki can't be done, is that correct?

**Comment by rfomin** [comment]
> As far as I know, PRs for the wiki can't be done, is that correct?

Yes, but you can just edit the wiki directly. Anyway, if it's more convenient for you, I can make a GitHib action with files renaming.

**Comment by kiwphi** [comment]
Let's keep the docs/ for now and see how it goes. If it's not too much of a hassle for you to do the Github Action, I'd be grateful for that.

**Comment by rfomin** [comment]
> If it's not too much of a hassle for you to do the Github Action, I'd be grateful for that.

Sure, no problem! @fabiangrefrath can we merge this?

**Comment by fabiangreffrath** [comment]
Yes please!

**Pull request merged**
