### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by mikeday0**
This started as simple proofreading but I expanded the scope a bit to correct a few assorted doc and man page issues that I noticed. Did I miss anything?

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Thank you!

**Comment by kiwphi** [comment]
While we're at it, any chance we could remove the first few lines of comments from cheats.md for the reasons discussed in https://github.com/fabiangreffrath/crispy-doom/issues/1041#issuecomment-1517985834

**Comment by fabiangreffrath** [comment]
> While we're at it, any chance we could remove the first few lines of comments from cheats.md for the reasons discussed in [#1041 (comment)](https://github.com/fabiangreffrath/crispy-doom/issues/1041#issuecomment-1517985834)

Sure, we can do that. The number of people which modify these files is rather limited, anyway. Can we  still keep this as a comment somewhere else in any other form, though?

**Comment by mikeday0** [comment]
Semi-related: anyone want to have a go at updating the [Doomwiki page](https://doomwiki.org/wiki/Crispy_Doom)? Just noticed it is pretty out-of-date.

**Comment by ceski-1** [comment]
[This page too](https://doomwiki.org/wiki/Comparison_of_source_ports).

**Comment by rfomin** [comment]
It should be someone with good English (not me 😆). The Woof page is outdated too.

**Comment by kiwphi** [comment]
The wiki pages look updated to me, besides the "Other games" section? Or do you mean it should become extensive and cover all the topics like the wiki?

**Comment by mikeday0** [comment]
The Other Games section is totally inaccurate.

**Comment by mikeday0** [comment]
Since it was trivial, I went ahead and submitted changes to the "Comparison of Source Ports" page.

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
