### PR TITLE
Implement reload / go to next level while demo playing

### PR DESCRIPTION
**Pull request by JNechaevsky**
Initial PR: https://github.com/JNechaevsky/international-doom/pull/27

Remaining TODO: no luck with proper music changing in Crispy code. Needs some investigation why, and probably will need some help here.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
We already have a `demowarp` feature. Could you try to use this instead?

**Comment by JNechaevsky** [comment]
Ah, got it. Yeah, we just running tics here as fast as possible, not indicating "go to this/that map" and stopping "full speed" right before player spawning in `P_SpawnPlayer`. 

Guess, it's your review-turn now, I have nothing to add technically, except few thoughts:

- Keys are working in demo loop. Could be useful for testing, or... Or is it a bad idea?
- No smooth demo bar while jumping. Which is good, because this making jumping as fast as it gets. And hey, demo bar is not drawing on top of wipes.

**Comment by JNechaevsky** [comment]
Small problem, not exactly related to this PR: framerate is forcefully uncapped after using `-warp` in demo playing, but `crispy->vsync` remains untouched.

**Comment by JNechaevsky** [comment]
To fix framerate capping issue, we have to extend [this condition](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/i_video.c#L1455):
```
// Turn on vsync if we aren't in a -timedemo
if ((!singletics && mode.refresh_rate > 0) || demowarp)
                                                ^^^^
```
Since demo warp is using `singletics`, which, in return, preventing vsync flag to be accounted. But this way `demowarp` must be externalized to upper level code, and the question is - where exactlly? Should it be `i_video.h` or `extern int demowarp` right in `SetVideoMode`?

**Comment by fabiangreffrath** [comment]
I don't think this will link with the non-Doom games if you introduce `demowarp` as only an `extern` in the `i_video.c` context. You'll wither need a `demowarp` instantiation in each game, or you instantiate it in `i_video.c` itself.

**Comment by JNechaevsky** [comment]
Pardon me, it's far simpler as `demowarp` is a part of `crispy_t` structure. This will fix capping issue without any externals:
```
    // Turn on vsync if we aren't in a -timedemo
    if ((!singletics && mode.refresh_rate > 0) || crispy->demowarp)
                                                  ^^^^^^^^^^^^^^^^
```
We can't move it to condition below since `!singletics` is doing it's job.

**Comment by fabiangreffrath** [comment]
Well then.

**Comment by turol** [comment]
Please put `extern` in a header where it's also visible to the actual declaration. This helps the compiler catch bugs. The `check-extern.sh` script checks this. It's enabled in CI for Chocolate but not for Crispy.

**Comment by JNechaevsky** [comment]
@turol, understood for future, thanks.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by JNechaevsky** [comment]
Thanks for approval! Can we merge it now? On next PR I would like to implement IDCLEV'ing to any levels, not just next ones while demo playback, it's fairly simple (https://github.com/JNechaevsky/international-doom/commit/faeb5a960bc64387924d83e33273e74e8c8e0389). 

For almost a week I was wondering what else can be done regarding demo playback, but no, nothing, zero ideas. Looks likes current features covers all possible needs, at least for simple wathching.

So far, info for changelog. Please correct my wording if needed:

- If vsync is active, framerate no longer forcefully uncapped after using demo warp (i.e. `-playdemo demo.lmp -warp xx`)
- Improved Crispy shortcut keys behavior while demo playback:
  - Restart level/demo: now restart demo but keeps it playing.
  - Go to next level: now warping to next level and keeps demo playing.

**Comment by fabiangreffrath** [comment]
> Thanks for approval! Can we merge it now?

That's what "aprroval" means, right? 😉

**Comment by JNechaevsky** [comment]
> That's what "aprroval" means, right? 😉

Nothing can do with myself, I have a huge fondness for subordination when changing code in Crispy. ☺️

**Pull request merged**
