### PR TITLE
Implement basic Hexen Crispness menu

### PR DESCRIPTION
**Pull request by mikeday0**
... and I definitely mean basic:
Screenshot from 2022-01-30 22-26-58

I wasn't able to successfully change the text color using `dp_translation`. Most `CR_` indices yielded dark text, not colored as expected. Any ideas? Hexen PLAYPAL shenanigans?

Other than that everything seems to be functioning as expected.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Crispy's color translation tables are not static. You'll need to initialize them at engine start up:
https://github.com/fabiangreffrath/crispy-doom/commit/a498866968f65ca88c9004541fe92763deadbdf3

**Comment by fabiangreffrath** [comment]
Will this need a different background pattern for the demo version or for the DK addon?

**Comment by mikeday0** [comment]
Thanks for the tip on the color tables. How about something like this?
Screenshot from 2022-01-31 21-22-43

> Will this need a different background pattern for the demo version or for the DK addon?

Shouldn't. The demo HEXEN.WAD has the appropriate lump and DK runs with HEXEN.WAD as an IWAD. (Just tested both)

**Comment by fabiangreffrath** [comment]
> Thanks for the tip on the color tables. How about something like this? 

Neat!

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
