### PR TITLE
Add key binding for toggling mouselook

### PR DESCRIPTION
**Pull request by StevenSYS**
Makes toggling mouselook bindable to a key.

Doom Demo:

https://github.com/user-attachments/assets/9adbfba3-5817-4ffc-8aea-ed6b8f326c20

Heretic Demo:

https://github.com/user-attachments/assets/cc8df8bc-4a88-4fdc-8b8d-453733105210

Hexen Demo:

https://github.com/user-attachments/assets/87d2be82-d7dc-492a-a928-5467dc2b7715

Strife Demo:

https://github.com/user-attachments/assets/0a667bb0-5ccc-4de4-a6f8-60dc15ff09f8

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Doesn't this collide with the `mousebmouselook` concept somehow?

**Comment by StevenSYS** [comment]
I didn't know that `mousebmouselook` existed until now.

**Comment by StevenSYS** [comment]
I've closed this PR because I think this feature is really needed.

**Comment by seascape** [comment]
I came today to ask for exactly this feature. I'll post here rather than create a new issue.

As a semi-purist I don't use mouselook often but it IS a feature in classic Heretic that I wanted to use in non-combat moments to look around for secrets and better "platforming."

Currently mouselook can only be toggled by a mouse bind. This hasn't proved useful because my L/R/M mouse buttons and mousewheel up/down are all occupied doing important things already, and crispy-heretic-setup (and by extension probably Crispy Heretic itself?) does not recognize my mouse's Mouse 4 and Mouse 5 side buttons.

Normally I could work around even this situation by using X-Mouse Button Control (terrific utility app) or AutoHotKey or the like to map Mouse 4 / Mouse 5 to send simulated keyboard inputs that could then invoke a Crispy Heretic keyboard mapping. But since there is no keyboard mapping to toggle mouselook that isn't possible. 

This mapping not being available feels like a small oversight in my opinion. In my case it's preventing me from using mouselook as I don't wish to have mouselook enabled normally, only now and then. Thanks for considering.

(Mouse 4 and Mouse 5 support, if it indeed doesn't exist, would be a separate but similar recommendation to add. Lots of people have these buttons and they're very handy in games.)

**Comment by turol** [comment]
> Mouse 4 and Mouse 5 support, if it indeed doesn't exist

Works for me on Linux.

**Pull request closed without merging**
