### PR TITLE
quicksave to classic savegame slot, but skip questions

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thanks @OpenRift412 for the suggestion!

@rfomin How would you like this solution for Woof? It's a middle ground between classic Vanilla Doom behaviour and "real" quicksave but a less drastic change that our current solution.

Also pulling @kraflab into the discussion if they want to join.

**Comment by fabiangreffrath** [comment]
Fixes #831

**Comment by kraflab** [comment]
It's not clear to me what the purpose of this change is, or how the existing behaviour "limits the usefulness" of the feature, and it costs more lines of code :^) 🤷

**Comment by OpenRift412** [comment]
> It's not clear to me what the purpose of this change is, or how the existing behaviour "limits the usefulness" of the feature, and it costs more lines of code :^) 🤷
> 
> Of course, that's just my stance for dsda-doom :^)

It lets you quicksave to more than just a single dedicated slot, which makes quicksaving far more useful. It would especially be worth having in DSDA because of the _ridiculuous_ amount of standard save slots available. It'd be a waste not to put them to use.

**Comment by kraflab** [comment]
If you want to have multiple saves you would just save to a slot and then keep using quicksaves...it's essentially identical. I strongly suspect the pattern used by almost every game works completely fine 😸

**Comment by OpenRift412** [comment]
> If you want to have multiple saves you would just save to a slot and then keep using quicksaves...it's essentially identical. I strongly suspect the pattern used by almost every game works completely fine 😸

The only games that come to mind that use that system is Quake 1 and 2 and Doom 64 on KEX. 

Let's say you're playing multiple WADs, switching back and forth. You'd have to remember to save your game the long way before you stop playing one WAD and switch to another. Otherwise, when you quicksave while playing another WAD you'd lose all the progress you gained from the other WAD you've been playing. It just seems a lot more counter-intuitive from a design standpoint.

**Comment by kraflab** [comment]
> Let's say you're playing multiple WADs, switching back and forth. You'd have to remember to save your game the long way before you stop playing one WAD and switch to another. Otherwise, when you quicksave while playing another WAD you'd lose all the progress you gained from the other WAD you've been playing. It just seems a lot more counter-intuitive from a design standpoint.

Save files for different wads are stored completely separately in dsda-doom by default, so this is imposssible 😉

**Comment by OpenRift412** [comment]
> Save files for different wads are stored completely separately in dsda-doom by default, so this is imposssible 😉

Well that sounds like it could be _a lot_ more bloated than this solution, but suit yourself I guess.

**Comment by kraflab** [comment]
Save file conflicts are a serious and annoying problem that affects everyone that uses the port though, so a complete solution is quite beneficial for many people. It's a completely separate topic and has nothing to do with this PR.

**Pull request merged**
