### PR TITLE
hexen: Don't align swiping weapons

### LINKED ISSUE #1039: (Hexen) Some weapon animations don't seem to be working properly
### Background

Version of Crispy Doom: 6.0.0

Operating System and version: Windows 7 Home Premium x64

Game: Hexen

Any loaded WADs and mods (please include full command line): None

### Bug description

Observed behavior: I'm not sure how to explain this properly, but I'll try. In any case, you can try it yourselves and compare against DOS or Chocolate Hexen.

The Fighter and Cleric's starting weapons (mace and fist respectively, sorry if I got the names wrong) have certain frames that I believe are supposed to maintain one given sprite but be moved constantly until they're offscreen (in the case of the Fighter's fist, this seemingly happens upon dealing three consecutive hits). However, this effect is not present, and the weapon sprite remains static for a bit until you can attack again.

Expected behavior: Same behavior as in DOS/Chocolate.

### PR DESCRIPTION
**Pull request by mikeday0**
Fixes #1039.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
While this is most definitely correct, I wonder if there's a more general way to detect these.

**Comment by mikeday0** [comment]
I agree that there should be a more elegant solution. Maybe something with analyzing the trajectory of the sprites during the animation sequence?

**Comment by JNechaevsky** [comment]
Probably check if `misc1` and `misc2` of PSP states are above zero ([these ones](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/info.h#L3187))? If I'm getting things right, they are used to set PSP coords [here](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/p_pspr.c#L235-L242).

**Comment by mikeday0** [comment]
@JNechaevsky Congrats on CRL! I was playing with it yesterday, very nice work!

I think the sprite path is set both by sprite offsets and the `misc1` and `misc2` values. For example you can zero out all the SPR_FPCH `misc1` and `misc2` values and still see a punch which travels from right to left. (Albeit in a very choppy fashion.)

**Pull request merged**
