### PR TITLE
Fix playing music other than in MUS/MIDI format (on Windows)

### PR DESCRIPTION
**Pull request by rfomin**
Tested with SIGIL_SHREDS.wad

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Is this somehow specific to Crispy or would this apply to Choco as well?

**Comment by rfomin** [comment]
> Is this somehow specific to Crispy or would this apply to Choco as well?

I think Choco doesn't support mp3/ogg/flac lumps in WADs, so this is specific to Crispy.

**Comment by fabiangreffrath** [comment]
Thank you!

**Comment by fabiangreffrath** [comment]
Does Woof need a similar fix?

**Comment by rfomin** [comment]
No, Woof doesn't need it.

**Comment by fabiangreffrath** [comment]
So I consider Woof ready for release. What do you say?

**Comment by rfomin** [comment]
> So I consider Woof ready for release. What do you say?

Yes, it's ready. Can we distribute it with fluidsynth or is it too many DLLs?

**Comment by fabiangreffrath** [comment]
Not only would we need additional libraries but also a suitable soundfont and a way to configure fluidsynth to use that soundfont by default.

**Comment by rfomin** [comment]
Fluidsynth supports DLS files, so we could use the same sound font as the Microsoft GS synth https://github.com/FluidSynth/fluidsynth/pull/493
I think we can add soundfont path settings in the config.

**Comment by fabiangreffrath** [comment]
This will need some patching.

**Comment by rfomin** [comment]
Yes, I may not be in time for this version. I'll try tomorrow.

**Comment by rfomin** [comment]
I tried but for some reason `C:\Windows\System32\drivers\gm.dls` sounds really bad with fluidsynth. Maybe not worth it.

**Pull request merged**
