### PR TITLE
Ability to load saved game when a netgame demo is playing

### PR DESCRIPTION
**Pull request by JNechaevsky**
By the request of @fabiangreffrath.
Discussion: https://github.com/fabiangreffrath/crispy-doom/issues/198.

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Dang. I've got some kind of desync... Only the latest one is necessary: https://github.com/fabiangreffrath/crispy-doom/pull/205/commits/6c6646cbe6eb88c3b5c04b4efa52dc20b50bff70

**Comment by fabiangreffrath** [comment]
Thank you! I will pick this commit during my 4.1-release clean-up.

So, could you confirm that it is possible to save multiplayer games but then impossible to load them (except from the command line or what)?

**Comment by fabiangreffrath** [comment]
Merged, thanks!

https://github.com/fabiangreffrath/crispy-doom/commit/0d20ff0282ee706e7ae68c208aef390d728f5672

**Comment by JNechaevsky** [comment]
My pleasure! Sorry for late reply and this little inconvenience with additional commits, I'm still not very experienced on working between forked version <> main project. Probably I should always commit anything to my forked version first, otherwise GitHub Desktop will give some weird desync errors.

Yes, it is able to save multiplayer game (I was testing using -solo-net), but impossible to load it in game. Loading is only available through: `crispy-doom.exe -solo-net -loadgame 0`. But it does not seems to be matter here, since we need to start a new game to get a loading ability. In other words, demo playback of multiplayer demos does not prohibits starting a new game.

**Comment by JNechaevsky** [comment]
Yes, `-loadgame 0 -solo-net` working, but loaded game becomes single player in all aspects.

**Comment by Zodomaniac** [comment]
BTW, if the game is singleplayer and MM in-built demo starts, the Load Game menu becomes shaded (though it works)

**Comment by fabiangreffrath** [comment]
> Yes,  -loadgame 0 -solo-net  working, but loaded game becomes single player in all aspects.

Crap! That's what I was afraid of. Should be fixed with the next commit.

> BTW, if the game is singleplayer and MM in-built demo starts, the Load Game menu becomes shaded (though it works)

This as well, good catch!

**Pull request closed without merging**
