### PR TITLE
Heretic & Hexen: even more automap improvements

### PR DESCRIPTION
**Pull request by JNechaevsky**
Make Automap great again! ☕

### CODE REVIEW

**Comment by JNechaevsky** [comment]
I think it's all done at this point. One important question though: do we need a line anti-aliasing for automap grid?

- For aesthetic reason: yes, we do. In InterH&H I have applied anti-aliasing to all existing lines, even to those which wasn't smooth in original games (example [screenshot](https://user-images.githubusercontent.com/21193394/175999880-e9ad9bf8-b2b8-4bf7-86d7-8706b545147e.png)).
- For technical reason: no, we don't. Non anti-aliased grid gives far better, pixel-perfect picture of BLOCKMAP alignment. Grid itself is mostly about BLOCKMAP checking, it's not just a _nice_ thing to have or use.

So what we would like to choose?

**Comment by fabiangreffrath** [comment]
I could live without interpolated grid lines. 😉

**Comment by JNechaevsky** [comment]
Albright, then we are all done here! Or should we increase `F2_PANINC` to `12` in this PR as well? I'm still in chat-only mode until evening.

And by the way: 4 days left before two week vacation. 🤩 According to the weather reports, first week will be about +30° (oh no!), second about rainy +20° (yay!).

**Comment by fabiangreffrath** [comment]
> Albright, then we are all done here!

Thank you!

> Or should we increase `F2_PANINC` to `12` in this PR as well? 

No, I'll apply this directly after merging.

> And by the way: 4 days left before two week vacation. 🤩 According to the weather reports, first week will be about +30° (oh no!), second about rainy +20° (yay!).

My vacation will be in three weeks. 💪 I have to say, I am the +30°C guy, but only when I am free - during working times it's pure pain of course. I love summer and can have 20°C and rain during each other season of the year. 😉

**Comment by JNechaevsky** [comment]
Sigh. Wish I say "let's change!", but in current situation in our... _"wunderland"_ this will be something like a bad ethics. 

Oh well, second cup of coffee is here, so let's just finish Automap stuff. 🗺️ It was a nice ride, I believe we have everything reasonable what can be done. Except, maybe a ~~coffee~~ tea timer, but let's keep this idea for possible future port. 🤓

**Pull request merged**
