### PR TITLE
Update CodeBlocks project version to 4.3

### PR DESCRIPTION
**Pull request by JNechaevsky**
Sorry for it takes forever, again.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I am not merging this, yet, as I don't want to waste your time. As you might have seen, I am currently preparing this:

https://github.com/fabiangreffrath/crispy-doom/tree/sdl2-branch

**Comment by JNechaevsky** [comment]
Oh, I haven't seen. It's a great news, and I think I have great news too. Take a look at [this screenshot](http://screenshot.ru/upload/images/2017/10/09/yeahac5c7.png)! SDL2 adaptation for CodeBlocks takes about 5 minutes, and I think I'm the first one who is playing SDL2 Crispy on Windows. :)

First impressions are as great as expected - now there is a much better game picture in fullscreen mode, uncapped/vsync framerates are working just fine w/o overloading CPU, and of course, `alt+enter` plays it's role. Yep, as it was spoken before, it's a huge step forward.

Maybe you should reject this PR completely - I will prepare a new one for SDL2 just when it's time will come and you give me a signal. If I'll forget to do this, please feel free to kick me in the knee.

**Comment by fabiangreffrath** [comment]
> Maybe you should reject this PR completely - I will prepare a new one for SDL2 just when it's time will come and you give me a signal. If I'll forget to do this, please feel free to kick me in the knee.

Now is the right time, I just merged the sdl2-branch!

**Comment by JNechaevsky** [comment]
Excellent! Just before I move on, please clarify two moments:

1. Version number should be 4.4? Not a 4.3 since it was the last one with SDL1?
2. Should I add these strings to `codeblocks/config.h`?

```
/* Declare netcode-compatibility with Chocolate Doom */
#define NET_PACKAGE_STRING "Chocolate Doom 2.3.0"
```

**Comment by fabiangreffrath** [comment]
> Version number should be 4.4? Not a 4.3 since it was the last one with SDL1?

Neither. The canonical location for the version number is in 
https://github.com/fabiangreffrath/crispy-doom/blob/master/configure.ac

It will be at least `5.0` and is currently at `5.0-beta`.

> Should I add these strings to codeblocks/config.h?

No, this will never be required again. \o/

**Pull request closed without merging**
