### PR TITLE
Heretic: support dedicated music tracks for each map

### PR DESCRIPTION
**Pull request by kitchen-ace**
Thanks to Dwars for the suggestion.

### CODE REVIEW

**Comment by kitchen-ace** [comment]
I wasn't sure how to best approach this, since Heretic has music tracks for all its levels defined in the array sounds.c, so I opted to make it a 2D array with the alternative track name, when it might exist, in the second "column." There might be a better approach?

This produces a whole lot of `sounds.c:30:28: warning: missing braces around initializer [-Wmissing-braces]` errors, which I'm not sure how to fix; it compiles and works fine though.

**Comment by fabiangreffrath** [comment]
I like this approach and I'm going to merge it. However, we will not get it through Travis CI with this warnings. Please try to fix them.

**Comment by fabiangreffrath** [comment]
The `MUSIC` macros are actually structs. I guess you'll have to put brackets around the `NULL` initializers.

**Comment by kitchen-ace** [comment]
>I guess you'll have to put brackets around the NULL initializers.

Ah, that did the trick. Thanks!

**Comment by fabiangreffrath** [comment]
Forgot to say thank you!

**Pull request merged**
