### PR TITLE
Update changelog

### PR DESCRIPTION
**Pull request by mikeday0**
@JNechaevsky @fabiangreffrath Probably missed some things. :smile: Comments welcome. Or, feel free to commit to this branch directly.

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Yeah, composing changelog is always most unexciting, bureaucratic challenge! 😅 

Better I keep my hand off, until I broke something in multiple branches as usual. Couple of thing comes to mind:
* Heretic and Hexen: all automap improvements are available in these games as well (great again!).
(https://github.com/fabiangreffrath/crispy-doom/pull/907)
* Heretic and Hexen: fixed background parallax 
(https://github.com/fabiangreffrath/crispy-doom/pull/911)
* Heretic: fixed potential crash on running on x64 systems.
(https://github.com/fabiangreffrath/crispy-doom/commit/c14260fdcf20fa5a152aea1e095c9d8d128cb7cb)

Also, these changes can be clarified a bit:
```
* Brightmaps for mid-textures (by @JNechaevsky).
     to:
* Brightmaps now working on mid-textures of two-sided lines (by @JNechaevsky).
```
and
```
* Improved brightmap implementation (by @JNechaevsky).
    to:
* Brightmap now also applied to SW2HOT texture and improved brightmaps of SILVER3, COMPUTE2 and COMPUTE3 textures (by @JNechaevsky).
```

**Comment by mikeday0** [comment]
Thanks for the suggestions! Take a look at the latest version and let me know if anything is incorrect.

I intentionally did not mention the automap parallax because if I'm not mistaken it was only an issue in development builds.

**Comment by JNechaevsky** [comment]
Thanks @mikeday0! I have nothing to add. 🤝

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
