### PR TITLE
Hexen uncapped framerate

### PR DESCRIPTION
**Pull request by mikeday0**
In progress.

### CODE REVIEW

**Comment by mikeday0** [comment]
Struggling a bit with the polyobject interpolation. Going to try a different approach this weekend.

**Comment by mikeday0** [comment]
I'm calling this done. (For now, at least.) Submitting for review!

**Comment by JNechaevsky** [comment]
Oh, there is one more thing I want to point your attention - sky scrolling. It is always scrolling by one texture pixel, not by screen pixel, and thus, it's not really smooth. I've done smooth scrolling without `fractionaltic`, but there is still small magic number because of variable speed.

This mess may be handy:
https://github.com/JNechaevsky/inter-doom/blob/master/src/hexen/r_plane.c#L555-L563 (have a look at `smooth_sky`).

AFAIR, my trick was avoiding `offset` and instead, using `Sky1/2SmoothScrollDelta` for smooth scrolling.

**Comment by mikeday0** [comment]
I made an attempt at the sky scrolling but I found the scrolling speed to be too slow to be smoothly interpolated. From what I can tell, the fastest sky scroll rate in vanilla Hexen is 0.3125 texture pixels per gametic. (Defined after the sky* markers in the MAPINFO lump; multiply the values by 256 and then divide by FRACUNIT.) Or in other words, the scrolling advances one texture pixel every 3 or 4 gametics. The best I can do at double resolution is scroll 0.625 screen pixels per gametic, or one screen pixel every 1 or 2 gametics (usually 2). That's not exactly smooth. So for now I deemed this not worth it.

I might come back to it later, as I do hate giving up on a problem. :smile: Question - does your implementation change the scrolling speed based on frame rate? I would really like to figure out a way to keep the scrolling speed the same as vanilla, in line with the Crispy philosophy.

**Comment by JNechaevsky** [comment]
Nope, I was avoiding usage of `fractionaltic` for flats and sky drawing. Have a look, it's all done in `P_AnimateSurfaces` [here](https://github.com/JNechaevsky/inter-doom/blob/master/src/hexen/p_anim.c#L199-L225), and it have to be framerate independent.

I've made some tests for planes scrolling by placing original scroller and my one nearby. Speed almost equal, except my one is about ~5% slower. As about skies, well, here I've done just a brief tests with recording two videos and comparing scrolling speed by my eyes, like "these sky pixels is here, and after 5 seconds they are there". 👀 So yeah, it looks smooth, but probably not 100.00% identical to vanilla, but still very, very close to it.

**Review by fabiangreffrath — APPROVED** [review]
LGTM. And looks like a massive effort, thank you very much for this!

**Comment by mikeday0** [comment]
@JNechaevsky Sorry for all the dumb questions. I was thinking you were somehow interpolating without using `fractionaltic` and I was very confused. In fact, with your implementation you are just advancing the scrolling every `gametic`, correct? That makes a lot more sense, and of course would not be dependent on the framerate. Thank you again for explaining everything.

@fabiangreffrath This is ready for merging. I see that I now have a merge button but I don't dare try it myself without your permission! :)

**Comment by fabiangreffrath** [comment]
Thank you very much! I have given you dev access, so you may of course merge a pull request if you consider it ready - as long as you take care of the bugs it introduces. 😉

**Comment by JNechaevsky** [comment]
@mikeday0, there is nothing dumb at all! Actually, yes, turns out my approach makes scrolling smoother and better than original one, and allows to scroll any floor texture w/o Tutti-Frutti effect (yay!). But in fact, it's _"smooth"_ because of `ds_*frac` is moving very softly, but technically it's not _"interpolated"_, because of no `fractionaltic` is used at all.

Yes, you absolutely correct, I'm scrolling skies/planes via `P_AnimateSurfaces`, which is called in `P_Ticker`, which is called in `G_Ticker` while level is running. 😊

**Comment by JNechaevsky** [comment]
Colleagues, I have a small question left, please. Not because of something is wrong about it, but because of lack of my knowledge, wondered long time about it, but always forgot to know/ask.

What is the reason of making variable `static` inside the function like this https://github.com/fabiangreffrath/crispy-doom/blob/master/src/hexen/r_plane.c#L403? It's also present in original code like this: https://github.com/fabiangreffrath/crispy-doom/blob/master/src/doom/am_map.c#L1191

If I'm getting things right, if a variable is declared strictly inside of function, it can't be used outside like `extern int interpfactor`? Or...?

**Comment by fabiangreffrath** [comment]
So it always keeps its current value even across subsequent calls of that function. In your second example, the f-word variable will keep on counting errors that occured when this function got called. It's like a global variable but only for that one function.

**Comment by JNechaevsky** [comment]
Ah, thanks, I think I've got it. In case of making `interpfactor` static, it's "smoothes factor" always will be set correctly, and not re-initialized with `0` after leaving `R_DrawPlanes`. This should set correct floor texture offset correctly, after a moment of visplanes weren't drawn.

**Comment by mikeday0** [comment]
Just a word of warning: local non-`static` variables in a function are not automatically re-initialized to 0! They will be garbage values, and if you fail to account for this it can lead to strange behavior in your function. You have to initialize or set them yourself.

**Comment by mikeday0** [comment]
Sorry, I just realized I completely failed to answer your question. 🤦‍♂️ The reason I made `interpfactor` static is to handle the case when the game is being paused. It retains the previously calculated value so that when the scrolling stops, it stops at the last calculated position instead of jerking to the previous non-interpolated position. Honestly it is a very minor issue but I wanted it to behave the same as the scrolling wall textures, which exhibit no such jerk.  Doing my part to keep jankiness to a minimum!

**Comment by JNechaevsky** [comment]
Yep, just I thought, thank you! For deeper understanding and practical use I definitely should play around with such variables and check/test the result. Even after about six years of amateur programming experience, 99% of which comes from working on Doom source code and asking a questions, my programming skill is still...amateur. Honestly, most of my successful implementations are based on luck/patience/fanatical and emotional pursuit, rather than calm and pure logic. 😱

**Pull request merged**
