### PR TITLE
Hexen: Support 8 pages of saves

### PR DESCRIPTION
**Pull request by mikeday0**

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
LGTM

**Comment by mikeday0** [comment]
A few comments.

#### Item 1:
I opted to use your Doom convention for the base save file names. That is, `hex<10*savepage + slot>.hxs`. This was done to avoid clashing with the existing "base slot" and "reborn slot" files which are set to `hex6.hxs` and `hex7.hxs` respectively. This save file numbering is different than what I did with Heretic and as a result it is now the odd man out among the three. Should I go back and change Heretic to match Doom and Hexen? The only downside of doing so is that a user will need to rename any existing slot 6 or 7 save files in order to get them to show back up in the list.

#### Item 2:
I found a bug with the automatic save description. It turns out that map number in Hexen is not hub-relative, but distinct for every map in the game. So for example when you advance to the next hub you don't go from hub 1 map x to hub 2 map 1. What happens instead is you go to hub 2 map y, where y is some distinct number not assigned to a previous map. I believe this breaks a strength length assumption in the automatic save description where that code expects the level number to only be one digit. 

The bug that I am seeing here is that when the map number is 10 or greater and you're playing as a fighter, there can be some wonky behavior when attempting to save in the last slot on the page. It does not generate the save description text and instead leaves the slot blank. You are unable to type anything and if it you hit enter it will just assign it the default description text. I can easily fix this by reducing "FIGHTER" to "FGHTR" but I mention here in case you might want to modify the naming convention in some other way.

**Comment by fabiangreffrath** [comment]
Good morning!

> Should I go back and change Heretic to match Doom and Hexen?

I don't think that's necessary. In the end, nobody cares what the savegame filenames are called. And if anybody asks, we needed a migration path for Heretic that we didn't need for the other games.

> I can easily fix this by reducing "FIGHTER" to "FGHTR" but I mention it here in case you might want to modify the naming convention in some other way.

Yes, please apply that fix. Hexen's savegame descriptions fields are too short for anything more meaningful anyway.

Thank you!

**Comment by mikeday0** [comment]
Okay, done!

**Pull request merged**
