### PR TITLE
Master Levles Support?

### PR DESCRIPTION
**Pull request by quakeguy123**
Hi Fabian,

As you know i wanted to ask you if it would be possible to add support for the Doom 2 Master Levels when they are merged into a single wad. What i mean by that is the Masterlevels official wad called "MASTERLEVELS.WAD" http://doomwiki.org/wiki/MASTERLEVELS.WAD However the wad is part of "Doom Classic Complete" Collection that came out only on PSN. I don't own a PS3, and not to mention that it would not be legal to extract the wad. I have read that ZDoom doesn't support it: http://forum.zdoom.org/viewtopic.php?f=15&t=35619 i just wanted to brig that to your attention, i don't know anything else other that what i have linked here.  I hope i correctly posted the Request, i have to go now.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hi there,

I am not sure if you are aware of this, but you posted this issue as a pull request to merge the hicol2 branch into the master branch. I guess this was unintended?

Back to topic: Actually, I already considered adding support for this WAD and already started implementing it, but then thought that nobody will ever use it anyway, because that WAD is practically unavailable, and abandoned it. 

Some further issue to consider: What should be the music for each map? Most of them are intended to replace MAP01, should they all play the same music? What are the par times for each map, all 30 secs?

**Comment by quakeguy123** [comment]
I'm sorry, it was completely unintended, if i can move my request i would. Please move it or even better delete it after the discussion is over.

Interesting. Well i don't know if the levels in that wad even have music to begin with, My personal preference always was since they are extra levels for doom 2 just copy doom 2 music in order on all maps. Or leave it as it is. As for the par times probably the same as Doom 2, all of that is just a guess. I wish someone would upload a video just so i can see what the levels look like. Do they even have an intermission screen?  Apparently the BFG edition recognizes that wad and gives it an ending text screen.

#define C8TEXT \
"CONGRATULATIONS YOU HAVE FINISHED... \n\n"\
"THE MASTER LEVELS\n" 
https://github.com/id-Software/DOOM-3-BFG/blob/master/doomclassic/doom/d_englsh.h#L551
Line 551

Bethesda should just release the wad for PC and that's that.

**Comment by fabiangreffrath** [comment]
AFAICT this ending text screen is all as far as support for the masterlevels.wad file in the BFG Edition goes. The WAD contains nothing more than the 20 single Master Levels PWAD files arranged into a MAP01-MAP21 order. No music, nothing else.

What I can do in Crispy is: (1) Detect that this PWAD has been loaded, (2) change the window title accordingly, (3) fix level names in Automap, (4) fix level sequence, i.e. consider the secret level in TEETH.WAD and (5) show the Doom 2 cast after MAP21.
I guess I will leave the music exactly as in Doom 2, which is wrong but there is no better guess. Regarding par times, I think I will set them to "SUCKS!" just s i did for MAP33.

I'll have a look into it, please let me know if you have further ideas.

PS: It might be interesting to know which music and par times blzut3 chose for his "xaser-approved" Master Levels patch, but I am not into ZDoom: http://maniacsvault.net/projects

**Comment by quakeguy123** [comment]
Hi Fabian,
Oh Wow! That's lazy i must say. 

I agree with all of this, you can do that how you see fit. Regarding the par times, you can set it to 30s, "SUCKS!", or don display the par time at all.

Thank you! 

Good idea! I tried this patch. It works. Which music there is depends what the option the person who patches the wad choses. I chose: Map order: "Doom Classic (PSN) w /Secret Exit Restored" and Music: "Doom Classic (Doom 2 Order)"

Other options include: 
Map order: 
"Doom Classic (PSN) Strict (Alphabetical wrt PC)"
"Playstation extended w/ Secret Exit Restored"
"Xbox extended w/ Secret Exit (Alphabetical)"
"Xbox Strict (18 maps)"
"Playstation Strict (13 maps)"
"Xaser"
"Xaser (w/ custom exit)"

Music:
"PC (More D_RUNNIN)"
"Blzut3's Picks (Requires doom2.wad)"
"Xaser's Picks (Requires doom.wad & doom2.wad)"

As for the PAR time, it doesn't display it at all it only displays "TIME" on the left.

This what the "MASTER.WAD" generated by the patch looks like in SLADE:
master

I don't have any further ideas about Master Levels but i have one more suggestion/idea, not related to the Master Levels.

**Comment by fabiangreffrath** [comment]
> Oh Wow! That's lazy i must say.

I hope not?! ;)

> I agree with all of this, you can do that how you see fit. Regarding the par times, you can set it to 30s, "SUCKS!", or don display the par time at all.

I'll leave it at "sucks!" for the time being. I have found par times for E1M10 and MAP33 on classicdoom, but still not for the Master Levels:
http://www.classicdoom.com/xboxspec.htm

> Thank you!

Thank you for the suggestion.

> Which music there is depends what the option the person who patches the wad choses.

Xaser's music progression relies on Doom 1 tracks, so I cannot use that. Blzut3's music progression only uses Doom 2 tracks, but then again this is maybe just as arbitrary as keeping the original Doom 2 order. So, for the time being, I'll stay with the latter.

**Pull request closed without merging**
